config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'

  resources :leads
  post '/change_lead_stage', to: "leads#change_lead_stage"
  resources :contacts
  resources :activities
  resources :notes, only: [:create, :destroy]
  resources :lead_backlogs, only: [:index]
  resources :goals, except: [:show] do 
    post 'create_user_goals_for_all', to: 'goals#create_user_goals_for_all'
    delete 'destroy_user_goals_for_all', to: 'goals#destroy_user_goals_for_all' 
  end

  resources :users, only: [:update]

  get '/progress', to: 'users#progress'
  get '/user_profile', to: 'users#user_profile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="footer-logo">
    <%= image_tag 'logo_flipper_negativo.png', class: "logo" %>
  </div>
  <div class="footer-social">

    <%= link_to root_path do %>
    <i class="fab fa-google-plus-g social-button text-center"></i>
    <% end %>

    <%= link_to root_path do %>
    <i class="fab fa-facebook-f social-button text-center"></i>
    <% end %>

    <%= link_to root_path do %>
    <i class="fab fa-instagram social-button text-center"></i>
    <% end %>

  </div>

</div>

app/views/shared/_navbar.html.erb
<% links_left = {
                } %>

<% links_right = {
                  } %>


<div class="nav-wrapper" id="nav-wrapper">
  <div class="navbar" id="navbar">
    <%= link_to root_path, class: "nav-item-logo" do %>
      <%= image_tag 'logo_flipper_negativo.png', class: "logo" %>
    <% end %>
    <div class="nav-items d-none d-lg-flex">
      <div class="nav-item-left">
        <!-- Links na lateral esquerda da navbar -->
        <% links_left.each do |text, path| %>
          <%= link_to text, path, class: "navbar-links" %>
        <% end %>
      </div>
      <div class="nav-item-right">
        <!-- Links na lateral direita da navbar -->
    <% if user_signed_in? %>
    <div class="level-box">
      <div class="progress">
        <div class="progress-bar progress-bar-striped" role="progressbar" style="width: <%= @progress %>%;" aria-valuenow="<%= @progress %>" aria-valuemin="0" aria-valuemax="100"></div>
      </div>
      <p class="navbar-level-left"><%= current_user.level %></p>
      <p class="navbar-level-right"><%= current_user.level + 1 %></p> 
    </div>
      <% links_right.each do |text, path| %>
        <%= link_to text, path, class: "navbar-links" %>
      <% end %>
        <%= link_to "Logout", destroy_user_session_path, class: "navbar-links", method: :delete %>
      <% else %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-links" %>
      <%= link_to t(".sign_in", default: "Criar Conta"), new_user_registration_path, class: "navbar-links" %>
    <% end %>
  </div>
</div>


    <!-- Mobile dropdown list -->
    <div class="nav-mobile d-none">
      <div class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bars"></i></a>
         <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
          <!-- Login / Logout links -->
             <% if user_signed_in? %>
                <% links_right.each do |text, path| %>
                  <%= link_to text, path, class: "dropdown-item" %>
                <% end %>
                <%= link_to "Logout", destroy_user_session_path, class: "dropdown-item", method: :delete %>
            <% else %>
                <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "dropdown-item" %>
                <%= link_to t(".sign_in", default: "Criar Conta"), new_user_registration_path, class: "dropdown-item" %>
            <% end %>

            <div class="dropdown-divider"></div>
            <% links_left.each do |text, path| %>
              <%= link_to text, path, class: "dropdown-item" %>
            <% end %>
            <div class="dropdown-divider"></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="sidebox">
  <div>
    <%= link_to user_profile_path do %>
      <div class="avatar-box">
        <% if current_user.photo.url %>
          <%= image_tag current_user.photo.url(:avatar), class:"sidebar-avatar" %>
        <% else %>
          <%= image_tag "profile-placeholder.png", class:"sidebar-avatar" %>
        <% end %>
          <p class="avatar-level"><%= current_user.level %></p>
      </div>
      <h5><%= current_user.name %></h5>
    <% end %>
  </div>
  <div>
    <%= link_to leads_path do %>
      <h1>
        <i class="fas fa-briefcase"></i>
      </h1>
      <p>Leads</p>
    <% end %>
  </div>
  <div>
    <%= link_to activities_path do %>
      <h1>
        <i class="fas fa-clipboard-list"></i>
      </h1>
      <p>Atividades</p>
    <% end %>
  </div>
  <div>
    <%= link_to contacts_path do %>
      <h1>
        <i class="fas fa-users"></i>
      </h1>
      <p>Contatos</p>
    <% end %>
  </div>
  <div>
    <%= link_to progress_path do %>
      <h1>
        <i class="fas fa-trophy"></i>
      </h1>
      <p>Progresso</p>
    <% end %>
  </div>
  <% if current_user.admin? %>
    <div>
      <%= link_to goals_path do %>
        <h1>
          <i class="fas fa-sliders-h"></i>
        </h1>
        <p>Gestão de metas</p>
      <% end %>
    </div>
  <% end %>
</div>