config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'

  resources :leads
  post '/change_lead_stage', to: "leads#change_lead_stage"
  resources :contacts
  resources :activities
  resources :notes, only: [:create, :destroy]
  resources :lead_backlogs, only: [:index]
  resources :goals, except: [:show] do 
    post 'create_user_goals_for_all', to: 'goals#create_user_goals_for_all'
    delete 'destroy_user_goals_for_all', to: 'goals#destroy_user_goals_for_all' 
  end

  resources :users, only: [:update]

  get '/progress', to: 'users#progress'
  get '/user_profile', to: 'users#user_profile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/lead.rb
class Lead < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :sales_funnel_stage
  belongs_to :lead_status
  has_many :contacts
  has_many :notes
  has_many :activities
  has_many :lead_backlogs
  
  before_create :set_lead_status
  before_create :set_sales_funnel_stage

  monetize :revenue_cents

  def self.filter_by_identifier(identifier)
    self.joins(:sales_funnel_stage).where('sales_funnel_stages.identifier = ?', "#{identifier}")
  end

  def lost?
    self.lead_status.identifier == 1
  end

  def won?
    self.lead_status.identifier == 2
  end

  def set_lead_status
    if self.lead_status.nil?
      self.lead_status = LeadStatus.find_by(identifier: 0)
    end
  end

  def set_sales_funnel_stage
    if self.sales_funnel_stage.nil?
      self.sales_funnel_stage = SalesFunnelStage.find_by(identifier: 0)
    end
  end
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :set_lead, only: [:show, :edit, :update, :destroy]
  
  def index
    @leads = Lead.all.order(updated_at: :desc)
  end

  def change_lead_stage
    @lead = Lead.find(params[:lead_id])
    previous_stage = @lead.sales_funnel_stage
    @stage = SalesFunnelStage.find_by(identifier: params[:stage_identifier])
    @lead.sales_funnel_stage = @stage

    if @lead.save && (previous_stage != @lead.sales_funnel_stage)
      @backlog = LeadBacklog.new(lead: @lead, user: current_user, previous_stage: previous_stage, new_stage: @lead.sales_funnel_stage, revenue: @lead.revenue)
      if @backlog.save
        @backlog.lead.user.gain_goals_points(@backlog)
      else
        flash['notice'] = "O lead #{@lead.business_name} já foi mudado para #{@lead.sales_funnel_stage.name} anteriormente."
      end
      respond_to do |format|
        format.json { render json: { lead_id: @lead.id, backlog_id: @backlog.id }, status: 200 }
      end
    else
      respond_to do |format|
        format.json { render json: { lead_id: @lead.id }, status: 410 }
      end
    end
  end

  def show
    @note = Note.new
    @activity = Activity.new
  end

  def new
    @lead = Lead.new(sales_funnel_stage: SalesFunnelStage.find_by(identifier: 0),
                     lead_status: LeadStatus.find_by(identifier: 0))
  end

  def create
    @lead = Lead.new(lead_params)
    if @lead.save
      redirect_to @lead
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @lead.update(lead_params)
      redirect_to @lead
    else
      render :edit
    end
  end

  def destroy
    @lead.destroy

    redirect_to leads_path
  end

  private

  def set_lead
    @lead = Lead.find(params[:id])
  end

  def lead_params
    params.require(:lead).permit(:business_name, :revenue, :closure_date, :user_id, :sales_funnel_stage_id, :lead_status_id, :website, :address, :city, :state)
  end
end

app/views/leads/_form.html.erb
<%= simple_form_for @lead do |f| %>
  <%= f.input :business_name, label: "Nome da Empresa" %>
  <%= f.input :revenue, label: "Receita previsível" %>
  <%= f.input :closure_date, as: :date, label: "Data de fechamento" %>
  <%= f.input :user_id, collection: User.all, label: "Vendedor responsável" %>
  <%= f.input :sales_funnel_stage_id, collection: SalesFunnelStage.all, label: "Estágio do Funil" %>
  <%= f.input :lead_status_id, collection: LeadStatus.all, label: "Status atual" %>
  <%= f.input :website, label: "Website" %>
  <%= f.input :address, label: "Endereço" %>
  <%= f.input :city, label: "Cidade" %>
  <%= f.input :state, label: "Estado" %>

  <% unless @lead.id %>
    <%= f.submit "Criar Lead", class: "btn btn-primary" %>
  <% else %>
    <%= f.submit "Editar Lead", class: "btn btn-primary" %>
  <% end %>
<% end %>

app/views/leads/_leads.js.erb
const changeFunnelStage = (leadId, stageIdentifier) => {
  console.log(leadId)
  console.log(stageIdentifier)
  $.ajax({
    url: `/change_lead_stage`,
    data: {
      "lead_id": `${leadId}`,
      "stage_identifier": `${stageIdentifier}`
    },
    dataType: "json",
    type: "POST",
    success: function (data) {
      console.log('success');
    },
    error: function (data) {
      console.log(data.errors);
    }
  });
}

const drag_start_handler = (event) => {
  /* Set data */
  console.log('drag')
  event.dataTransfer.effectAllowed = 'move';
  event.dataTransfer.dropEffect = "move"
  event.dataTransfer.setData('text/plain', event.target.id);
  console.log(event.dataTransfer.getData('text/plain'));
  
}

const ondrop_handler = (event) => {
  console.log("drop");
  var leadCardId = event.dataTransfer.getData("text");
  var leadCard = document.getElementById(leadCardId)
  var stageZone = event.currentTarget;
  var firstCard = stageZone.firstChild;

  stageZone.insertBefore(leadCard, firstCard);
  changeFunnelStage(leadCard.dataset["lead_id"], stageZone.dataset["identifier"])
  event.preventDefault();
}

const dragover_handler = (event) => {
  event.dataTransfer.dropEffect = "move"
  event.preventDefault();
}




const leadCards = document.getElementsByClassName("lead-card")
const stageZones = document.getElementsByClassName("stage-body")

for (var i = 0; i < leadCards.length; i++) {
  leadCards[i].addEventListener('dragstart', drag_start_handler, false);
}

app/views/leads/edit.html.erb
<h1>Editar Lead</h1>

<div class="container">
  <div class="row">
    <div class="col-12 col-md-4 offset-md-4">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/leads/index.html.erb
<div class="leads-container">
  <div class="header-bar d-flex">
    <h2>Leads:</h2>
    <%= link_to 'Adicionar Lead', new_lead_path, class: 'btn btn-primary' %>
  </div>

  <div class="sales-funnel-wrapper">

    <% SalesFunnelStage.all.each do |funnel_stage| %>
      <div class="stage-wrapper">
        <div class="stage-header">
          <p><%= funnel_stage.name %></p>
          <p><%= humanized_money_with_symbol(Money.new(funnel_stage.leads.pluck(:revenue_cents).sum), currency: "brl") %></p>
        </div>

        <div class="stage-body" ondrop="ondrop_handler(event)" ondragover="dragover_handler(event)" data-identifier="<%= funnel_stage.identifier %>">

          <% @leads.where(sales_funnel_stage: funnel_stage).each do |lead| %>

            <div id="lead-<%= lead.id %>" draggable="true" data-lead_id="<%= lead.id %>"class="lead-card <%= "lost-lead" if lead.lost? %> <%= "won-lead" if lead.won? %>">
              <%= link_to lead_path(lead) do %>
                <p><%= lead.business_name %></p>
                <p><%= humanized_money_with_symbol(lead.revenue) %></p>
              <% end %>
            </div>

          <% end %>

        </div>
      </div>
    <% end %>

  </div>
</div>


<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    <%= render(:partial => 'leads', :handlers => [:erb], :formats => [:js]) %>
  <% end %>
<% end %>

app/views/leads/show.html.erb
<div class="container">

<h1>Nome: <%= @lead.business_name %>
<%= link_to edit_lead_path(@lead.id), class: "edit-icon" do %>
  <i class="fas fa-edit"></i>
<% end %>
<%= link_to lead_path(@lead.id), method: :delete, class: "delete-icon", onclick: "if (!confirm('Você tem certeza que deseja deletar?')) { return false }" do %>
  <i class="fas fa-trash-alt"></i>
<% end %>
</h1> 

<p>Estágio: <%= @lead.sales_funnel_stage.name %></p>

<ul class="nav nav-tabs lavalamp mb-2" id="myTab" role="tablist">
  <div class="lavalamp-object ease" style="transition-duration: 0.2s; width: 139.656px; height: 40px; transform: translate(128.141px, 0px);">
  </div>
  <li class="nav-item lavalamp-item" style="z-index: 5; position: relative;">
    <a class="nav-link show active" id="notas-tab" data-toggle="tab" href="#notas" role="tab" aria-controls="notas" aria-selected="true" onclick="return false">Notas</a>
  </li>
  <li class="nav-item lavalamp-item" style="z-index: 5; position: relative;">
    <a class="nav-link show" id="atividades-tab" data-toggle="tab" href="#atividades" role="tab" aria-controls="atividades" aria-selected="false" onclick="return false">Atividades</a>
  </li>
</ul>

<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade active show" id="notas" role="tabpanel" aria-labelledby="notas-tab">
      <% @lead.notes.each do |note| %>
        <div class="notification">
          <% if note.user.photo.url %>
            <%= image_tag note.user.photo.url(:avatar), class:"avatar-large" %>
          <% else %>
            <%= image_tag "profile-placeholder.png", class:"avatar-large" %>
          <% end %>
          <div class="notification-content">
            <p><small><%= note.user.name %> - <%= note.created_at.strftime('%m/%e/%y | %l:%M %p') %></small></p>
            <p><%= note.description %></p>
            <p><small></small></p>
          </div>

          <div class="notification-actions">
            <%= link_to note_path(note), method: :delete do %>Delete <i class="far fa-trash-alt"></i><% end %>
          </div>
        </div>
      <% end %>

    <h5 class="section-title">Adicionar nova nota:</h5>
    <%= simple_form_for @note do |f| %>
      <%= f.input :description, label: "Nota" %>
      <%= f.input :lead_id, as: :hidden, input_html: { value: @lead.id } %>

      <%= f.submit "Criar nota", class: "btn btn-primary" %>
    <% end %>

  </div>
  <div class="tab-pane fade" id="atividades" role="tabpanel" aria-labelledby="atividades-tab">
    <ul>
      <% @lead.activities.each do |activity| %>
        <li>
          <%= link_to activity_path(activity) do %>
            <p><%= activity.title %></p>
            <p><%= activity.description %></p>
            <p><%= activity.date %></p>
          <% end %>
        </li>
      <% end %>
    </ul>

    <h4>Adicionar nova atividade:</h4>
    <%= simple_form_for @activity do |f| %>
      <%= f.input :title, label: "Título" %>
      <%= f.input :description, label: "Descrição" %>
      <%= f.input :contact_id, collection: @lead.contacts, label: "Contato" %>
      <%= f.input :date, as: :datetime, label: "Data e Horário" %>
      <%= f.input :lead_id, as: :hidden, input_html: { value: @lead.id } %>

      <%= f.submit "Criar atividade", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>


<h3>Contatos:</h3>
<ul>
  <% @lead.contacts.each do |contact| %>
    <li>
      <%= link_to contact_path(contact) do %>
        <p>Nome: <%= contact.name %></p>
      <% end %>
    </li>
  <% end %>
</ul>

<%= link_to 'Adicionar contato', new_contact_path(lead_id: @lead), class: "btn btn-primary" %>

<h3>Notas:</h3>




<h3>Atividades:</h3>






<%= link_to 'Voltar', leads_path, class: "btn btn-primary" %>

</div>