config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'

  resources :leads
  post '/change_lead_stage', to: "leads#change_lead_stage"
  resources :contacts
  resources :activities
  resources :notes, only: [:create, :destroy]
  resources :lead_backlogs, only: [:index]
  resources :goals, except: [:show] do 
    post 'create_user_goals_for_all', to: 'goals#create_user_goals_for_all'
    delete 'destroy_user_goals_for_all', to: 'goals#destroy_user_goals_for_all' 
  end

  resources :users, only: [:update]

  get '/progress', to: 'users#progress'
  get '/user_profile', to: 'users#user_profile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :lead, optional: true
  has_many :activities
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  def index
    @contacts = Contact.all
  end

  def show
  end

  def new
    if params[:lead_id]
      @contact = Contact.new(lead: Lead.find(params[:lead_id]))
    else
      @contact = Contact.new
    end
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to @contact
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @contact.update(contact_params)
      redirect_to @contact
    else
      render :edit
    end
  end

  def destroy
    @contact.destroy

    redirect_to contacts_path
  end

  private

  def set_contact
    @contact = Contact.find(params[:id])
  end

  def contact_params
    params.require(:contact).permit(:name, :phone, :email, :position, :lead_id)
  end
end

app/views/contacts/_form.html.erb
<%= simple_form_for @contact do |f| %>
  <%= f.input :name, label: "Nome do Contato" %>
  <%= f.input :phone, label: "Telefone" %>
  <%= f.input :email, label: "Email" %>
  <%= f.input :lead_id, collection: Lead.all, label_method: lambda {|t| t.business_name}, label: "Lead associado" %>
  <%= f.input :position, label: "Cargo" %>

  <% unless @contact.id %>
    <%= f.submit "Criar contato", class: "btn btn-primary" %>
  <% else %>
    <%= f.submit "Editar contato", class: "btn btn-primary" %>
  <% end %>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editar Contato</h1>

<div class="container">
  <div class="row">
    <div class="col-12 col-md-4 offset-md-4">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/contacts/index.html.erb
<div class="leads-container">
  <div class="d-flex">
  <h2>Contatos:</h2>
  <%= link_to 'Adicionar Contato', new_contact_path, class: 'btn btn-primary' %>
  </div>

    <table class="table">
    <thead>
      <tr>
        <th scope="col">Nome</th>
        <th scope="col">E-mail</th>
        <th scope="col">Telefone</th>
        <th scope="col">Posição</th>
        <th scope="col">Lead Associado</th>
      </tr>
    </thead>
    <tbody>
  <% @contacts.each do |contact| %>
    <tr>
      <%= link_to contact_path(contact) do %>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.position %></td>
      <% end %>
        <td><%= contact.lead.business_name if contact.lead %></td>
    </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/contacts/new.html.erb
<h1>Adicionar Lead</h1>

<div class="container">
  <div class="row">
    <div class="col-12 col-md-4 offset-md-4">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/contacts/show.html.erb
<h1>Nome: <%= @contact.name %></h1>

<p>Lead Associado: <%= link_to @contact.lead.business_name, lead_path(@contact.lead) if @contact.lead %></p>

<%= link_to edit_contact_path(@contact), class: "edit-icon" do %>
  <i class="fas fa-edit"></i>
<% end %>
<%= link_to contact_path(@contact), method: :delete, class: "delete-icon", onclick: "if (!confirm('Você tem certeza que deseja deletar?')) { return false }" do %>
  <i class="fas fa-trash-alt"></i>
<% end %>

<%= link_to 'Voltar', contacts_path, class: "btn btn-primary" %>