config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'

  resources :leads
  post '/change_lead_stage', to: "leads#change_lead_stage"
  resources :contacts
  resources :activities
  resources :notes, only: [:create, :destroy]
  resources :lead_backlogs, only: [:index]
  resources :goals, except: [:show] do 
    post 'create_user_goals_for_all', to: 'goals#create_user_goals_for_all'
    delete 'destroy_user_goals_for_all', to: 'goals#destroy_user_goals_for_all' 
  end

  resources :users, only: [:update]

  get '/progress', to: 'users#progress'
  get '/user_profile', to: 'users#user_profile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  belongs_to :lead
  belongs_to :contact, optional: true
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  def index
    @activities = Activity.all
  end

  def show
  end

  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.user = current_user
    if @activity.save
      if @activity.lead
        redirect_to lead_path(@activity.lead)
      else
        redirect_to @activity
      end
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @activity.update(activity_params)
      if @activity.lead
        redirect_to lead_path(@activity.lead)
      else
        redirect_to @activity
      end
    else
      render :edit
    end
  end

  def destroy
    @activity.destroy

    redirect_to activitys_path
  end

  private

  def set_activity
    @activity = Activity.find(params[:id])
  end

  def activity_params
    params.require(:activity).permit(:title, :description, :contact_id, :lead_id)
  end
end

app/views/activities/_form.html.erb
<h4>Adicionar nova atividade:</h4>
<%= simple_form_for @activity do |f| %>
  <%= f.input :title, label: "Título" %>
  <%= f.input :description, label: "Descrição" %>
  <%= f.input :date, as: :datetime, label: "Data e Horário" %>
  <%= f.input :lead_id, collection: Lead.all, label_method: lambda {|t| t.business_name}, label: "Lead associado" %>
  <% if @activity.lead %>
    <%= f.input :contact_id, collection: @activity.lead.contacts, label: "Contato" %>
  <% else %>
    <%= f.input :contact_id, collection: Contact.all, label: "Contato" %>
  <% end %>
  <%= f.submit "Criar atividade", class: "btn btn-primary" %>
<% end %>

app/views/activities/edit.html.erb
<h1>Editar Atividade</h1>

<div class="container">
  <div class="row">
    <div class="col-12 col-md-4 offset-md-4">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/activities/index.html.erb
<div class="leads-container">
  <div class="d-flex">
  <h2>Atividades:</h2>

  <%= link_to 'Adicionar Atividade', new_activity_path, class: 'btn btn-primary' %>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">Cod. Cliente</th>
        <th scope="col">Descrição</th>
        <th scope="col">Data</th>
        <th scope="col">Concluído</th>
      </tr>
    </thead>
    <tbody>

      <% @activities.each do |activity| %>
        <tr>
          <%= link_to activity_path(activity) do %>

            <td scope="row"><%= activity.user_id %></td>
            <td><%= activity.description %></td>
            <td><%= activity.date %></td>
            <td><%= activity.done %></td>

          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/activities/new.html.erb
<h1>Adicionar Atividade</h1>

<div class="container">
  <div class="row">
    <div class="col-12 col-md-4 offset-md-4">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/activities/show.html.erb
<h1><%= @activity.title %></h1>
<p><%= @activity.description %></p>
<p><%= @activity.date %></p>

<%= link_to edit_activity_path(@activity), class: "edit-icon" do %>
  <i class="fas fa-edit"></i>
<% end %>
<%= link_to activity_path(@activity), method: :delete, class: "delete-icon", onclick: "if (!confirm('Você tem certeza que deseja deletar?')) { return false }" do %>
  <i class="fas fa-trash-alt"></i>
<% end %>

<%= link_to 'Voltar', activities_path, class: "btn btn-primary" %>